In [5]:
# Stanadard library: 
import numpy as np

# Local library: 
import IO.reader

# Third-party library: 

In [6]:
# Following Tutorials of how to use the IO library to read txt or dcd trajectory

In [7]:
# Part 1 ------- How to extract force data in LAMMPS trajectory file in parallel:

# work_flow: A python list containing
# [((start nconfigs),(start,nconfigs)),((start,nconfigs) ...] 

start_at = 1 # The nth configuration to start with ( by default starts with 1st configuration)

work_load = 5000 # total number of configurations

num_cores = 2 # total number of cores assigned 

buffer_size = 2000 # total number of configuration read into memory at once for each time 

force_data_address = "Ref.force"

total_atoms = 512

work_flow = IO.reader.parallel_assignment(start_at,work_load,num_cores,buffer_size) 
# work_flow: A python list containing
# [((start nconfigs),(start,nconfigs)),((start,nconfigs) ...] 

output_lst = IO.reader.read_LAMMPS_traj_in_parallel(force_data_address,num_cores,total_atoms,work_load,first=1,buffer_size=buffer_size)

sum_sqr = 0

for output in output_lst:
    
    force_data = output.get()
 
    sum_sqr += np.sum(force_data**2) 

# sum of squares of force along each axis: (independent of number of cores used)
print ( sum_sqr)

# 1 core: 114023426.9771057
# 2 cores: 114023426.97710575 
# 4 cores: 114023426.9771057 
# 6 cores: 114023426.97710566

114023426.97710575


In [8]:
# Part 2 ------- How to extract data in a single column: 

txtfile = "Ref.eng"

num_lines = IO.reader.get_number_lines(txtfile)

# If return_numpy=True, numpy array type is return, other ctypes array is returned. 
eng_data = IO.reader.loadtxt(txtfile,num_lines,skiprows=0,return_numpy=True)

print (eng_data)

c_int(5000)
[-10.03411634 -10.04478241  -9.99082185 ... -10.09243442 -10.13237654
 -10.02792909]


In [12]:
# Part 3 ------- How to extract dcd trajectory: 

dcdfile = "test.dcd"

total_frames,total_atoms = IO.reader.call_read_dcd_header(dcdfile)

current_frame = 5 

print ("total_frames:", total_frames)
print ("total_atoms:", total_atoms)

# If return_numpy=True, numpy array type is return, other ctypes array is returned. 
xyz,box = IO.reader.call_read_xyz_box(dcdfile,current_frame,total_atoms,return_numpy=True)

print (box)
print (xyz)

total_frames: 2001
total_atoms: 512
[24.88359261 24.88359261 24.88359261]
[[23.91516   23.691532   2.8096325]
 [ 1.829452  19.534567  13.253174 ]
 [14.067855  22.89595    9.0977125]
 ...
 [23.559156   0.1353707 10.112161 ]
 [18.908758  20.618652   2.3341913]
 [ 2.8030653 11.0794325  9.205279 ]]
